[package]
name = "bita"
version = "0.1.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"

[dependencies]
clap = "*"
serde = "*"
serde_derive = "*"
rust-lzma = "*"
threadpool = "*"
num_cpus = "0.2"
curl = "*"
blake2 = "*"
atty = "*"
error-chain = "*"
protobuf = "*"