[package]
name = "bita"
version = "0.1.2"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "Tool for fast file synchronization over http."
repository = "https://github.com/oll3/bita"
readme = "README.md"
keywords = ["update", "swupdate", "synchronization", "delta-update"]
categories = ["command-line-utilities", "compression"]

[dependencies]
clap = "2.32.0"
rust-lzma = "0.4.0"
zstd = "0.4.22"
threadpool = "1.7.1"
num_cpus = "1.9.0"
curl = "0.4.19"
blake2 = "0.8.0"
atty = "0.2.11"
error-chain = "0.12.0"
protobuf = "2.3.0"
crossbeam-channel = "0.3.8"
