[package]
name = "bita"
version = "0.3.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "Differential file synchronization over http(s)."
repository = "https://github.com/oll3/bita"
readme = "README.md"
keywords = ["update", "swupdate", "synchronization", "delta-update"]
categories = ["command-line-utilities", "compression", "differential"]

[build-dependencies]
protoc-rust = "2.8.1"

[dependencies]
clap = "2.33.0"
blake2 = "0.8.1"
atty = "0.2.13"
protobuf = "2.8.1"
log = "0.4.8"
fern = "0.5.9"
chrono = "0.4.9"
brotli = "3.3.0"
futures-preview = {version = "0.3.0-alpha.19" }
tokio = "0.2.0-alpha.6"
hyper = {version = "0.13.0-alpha.4", features = ["unstable-stream"]}
hyper-rustls = "0.18.0-alpha.2"

rust-lzma = {version = "0.4.0", optional = true}
zstd = {version = "0.4.28", optional = true }


[dev-dependencies]
tempfile = "3.1.0"

[features]
default = []
lzma-compression = ["rust-lzma"]
zstd-compression = ["zstd"]
