[package]
name = "bita"
version = "0.6.2"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "Differential file synchronization over http(s)."
repository = "https://github.com/oll3/bita"
readme = "README.md"
keywords = ["sofware-update", "file-synchronization", "delta-update",  "differential"]
categories = ["command-line-utilities", "compression", "filesystem"]

[workspace]
members = [
  "bitar"
]

[dependencies]
clap = "2.33.0"
blake2 = "0.8.1"
atty = "0.2.14"
log = "0.4.8"
fern = "0.6.0"
chrono = "0.4.11"
futures-util = "0.3.4"
tokio = { version = "0.2.20", features = ["fs", "io-std", "sync", "io-util", "macros", "time", "rt-threaded"] }
bitar = { version = "0.6.2", path = "bitar" }
url = "2.1.1"
num_cpus = "1.13.0"
async-trait = "0.1.30"

[features]
default = ["default-tls"]
lzma-compression = ["bitar/lzma-compression"]
zstd-compression = ["bitar/zstd-compression"]
default-tls = ["bitar/default-tls"]
rustls-tls = ["bitar/rustls-tls"]
